"""Skill taxonomy and extraction for the ATS preview.

Flat keyword matching only — no ML, no fuzzy matching. Matching is
case-insensitive with word boundaries; multi-word terms are matched as
plain substrings with the same boundaries.
"""

# Keyword lists adapted from 5hivam123/smart-resume-analyzer (MIT)

import re

ROLE_KEYWORDS = {
    "Software Developer (SDE)": [
        "Python",
        "Java",
        "C++",
        "JavaScript",
        "TypeScript",
        "Data Structures",
        "Algorithms",
        "OOP",
        "System Design",
        "REST API",
        "Microservices",
        "SQL",
        "NoSQL",
        "Git",
        "Docker",
        "CI/CD",
        "Linux",
        "Agile",
        "Scrum",
        "Unit Testing",
        "Design Patterns",
        "Multithreading",
        "Debugging",
    ],
    "Data Scientist / ML Engineer": [
        "Python",
        "Machine Learning",
        "Deep Learning",
        "NLP",
        "Computer Vision",
        "TensorFlow",
        "PyTorch",
        "Keras",
        "Scikit-learn",
        "Pandas",
        "NumPy",
        "Matplotlib",
        "Statistics",
        "Feature Engineering",
        "Model Deployment",
        "MLOps",
        "SQL",
        "Big Data",
        "Spark",
        "Hadoop",
        "A/B Testing",
        "Data Visualization",
        "Jupyter",
    ],
    "Frontend Developer": [
        "HTML",
        "CSS",
        "JavaScript",
        "TypeScript",
        "React",
        "Next.js",
        "Redux",
        "Tailwind CSS",
        "Bootstrap",
        "Sass",
        "Webpack",
        "Vite",
        "Responsive Design",
        "Accessibility",
        "REST API",
        "GraphQL",
        "Jest",
        "Cypress",
        "Figma",
        "UI/UX",
    ],
    "Backend Developer": [
        "Node.js",
        "Express",
        "Python",
        "Django",
        "FastAPI",
        "Flask",
        "Java",
        "Spring Boot",
        "REST API",
        "GraphQL",
        "Microservices",
        "PostgreSQL",
        "MySQL",
        "MongoDB",
        "Redis",
        "RabbitMQ",
        "Kafka",
        "OAuth",
        "JWT",
        "Caching",
        "System Design",
        "Docker",
        "SQL",
        "NoSQL",
    ],
    "Full Stack Developer": [
        "HTML",
        "CSS",
        "JavaScript",
        "TypeScript",
        "React",
        "Node.js",
        "Express",
        "Next.js",
        "MongoDB",
        "PostgreSQL",
        "REST API",
        "GraphQL",
        "Redux",
        "Tailwind CSS",
        "Docker",
        "Git",
        "CI/CD",
        "AWS",
        "Agile",
        "WebSockets",
    ],
    "Data Analyst": [
        "SQL",
        "Excel",
        "Power BI",
        "Tableau",
        "Python",
        "Pandas",
        "NumPy",
        "Data Cleaning",
        "Data Visualization",
        "ETL",
        "Statistics",
        "Google Analytics",
        "A/B Testing",
        "Reporting",
        "Dashboards",
        "Data Warehousing",
        "BigQuery",
        "Looker",
    ],
    "DevOps / Cloud Engineer": [
        "AWS",
        "Azure",
        "GCP",
        "Docker",
        "Kubernetes",
        "Terraform",
        "Ansible",
        "Jenkins",
        "CI/CD",
        "Linux",
        "Bash",
        "Prometheus",
        "Grafana",
        "Monitoring",
        "Networking",
        "Infrastructure as Code",
        "Helm",
        "GitHub Actions",
        "Load Balancing",
        "Serverless",
    ],
    "Android Developer": [
        "Kotlin",
        "Java",
        "Android SDK",
        "Jetpack Compose",
        "MVVM",
        "Retrofit",
        "Room",
        "Firebase",
        "Coroutines",
        "Dagger",
        "Hilt",
        "Material Design",
        "Google Play",
        "REST API",
        "Gradle",
        "Unit Testing",
    ],
    "AI / GenAI Engineer": [
        "LLM",
        "LangChain",
        "RAG",
        "Prompt Engineering",
        "Hugging Face",
        "Transformers",
        "Embeddings",
        "Vector Database",
        "Pinecone",
        "FAISS",
        "OpenAI API",
        "Fine-tuning",
        "PyTorch",
        "TensorFlow",
        "NLP",
        "Semantic Search",
        "Streamlit",
        "FastAPI",
    ],
    "General / Fresher": [
        "Communication",
        "Teamwork",
        "Problem Solving",
        "Leadership",
        "Time Management",
        "Git",
        "SQL",
        "Excel",
        "Python",
        "Java",
        "HTML",
        "CSS",
        "JavaScript",
        "Data Structures",
        "OOP",
        "Internship",
        "Adaptability",
        "Critical Thinking",
        "Presentation",
        "MS Office",
    ],
}

# Flat, deduped, sorted union of every role list.
TAXONOMY = sorted(
    {term for terms in ROLE_KEYWORDS.values() for term in terms}, key=str.lower
)


def _term_pattern(term):
    # \w-style boundaries that also treat + and # as word characters so
    # "C++" does not match inside "C++11" and "Java" not inside "JavaScript".
    return re.compile(r"(?<![\w+#])" + re.escape(term) + r"(?![\w+#])", re.IGNORECASE)


_PATTERNS = [(term, _term_pattern(term)) for term in TAXONOMY]


def extract_skills(text: str) -> list[str]:
    """Return the sorted taxonomy terms present in the text."""
    return [term for term, pattern in _PATTERNS if pattern.search(text)]
